name: detective
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  path: ^1.7.0
  args: ^2.1.1
  uuid: ^3.0.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4


executables:
  detective:
